# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: altis
      - task: tanoa
      - task: takistan
  altis:
    cmds:
      - cp -r co10_Escape_CUP_RU_vs_BAF0.Altis/ '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/'
      - cp -r common/* '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/co10_Escape_CUP_RU_vs_BAF0.Altis'
  tanoa:
    cmds:
      - cp -r co10_Escape_CUP_RU_vs_BAF2.Tanoa/ '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/'
      - cp -r common/* '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/co10_Escape_CUP_RU_vs_BAF2.Tanoa'
  takistan:
    cmds:
      - cp -r co10_Escape_CUP_RU_vs_BAF22.Takistan/ '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/'
      - cp -r common/* '/mnt/c/Users/rober/Documents/Arma 3 - Other Profiles/mitch/mpmissions/co10_Escape_CUP_RU_vs_BAF22.Takistan'